Uri encode settings
davidbarsky/sigv4 pull request #6
Opened 2021-05-11 19:34 UTC by rcoh

Some AWS services require double-encoding URIs.

2021-05-11 19:57 UTC, davidbarsky requested changes

2021-05-11 19:57 UTC, davidbarsky commented on aws-sigv4/src/types.rs
> +}
no need to have a helper/standalone function for this—i'd just inline this

2021-05-11 19:57 UTC, davidbarsky commented on aws-sigv4/src/types.rs
> +const PATH: &AsciiSet = &CONTROLS
what's... this doing?

2021-05-11 19:57 UTC, davidbarsky commented on aws-sigv4/src/types.rs
> +use percent_encoding::{utf8_percent_encode, AsciiSet, CONTROLS};
move this up to the top of the file?

2021-05-11 19:57 UTC, davidbarsky commented on aws-sigv4/src/lib.rs
> +    /// in the canonical request in order to pass a signature check.
```suggestion
    /// We assume the URI will be encoded _once_ prior to transmission. Some services
    /// do not decode the path prior to checking the signature, requiring clients to actually _double-encode_
    /// the URI in creating the canonical request in order to pass a signature check.
```

Nit: what services?

2021-05-11 19:57 UTC, davidbarsky commented on aws-sigv4/src/lib.rs
> +    double_uri_encode: bool,
Maybe make this an a non-exhaustive enum describing what the behavior should be, instead of a boolean?

2021-05-11 19:57 UTC, rcoh commented on aws-sigv4/src/lib.rs
> +    /// in the canonical request in order to pass a signature check.
there is no conclusive list 💀

2021-05-11 19:58 UTC, rcoh commented on aws-sigv4/src/types.rs
> +const PATH: &AsciiSet = &CONTROLS
it's how you configure the percent encode crate, sadly.

2021-05-11 20:23 UTC, davidbarsky commented on aws-sigv4/src/types.rs
> +const PATH: &AsciiSet = &CONTROLS
mind adding that as a comment above this?

2021-05-13 18:17 UTC, davidbarsky approved these changes

2021-05-13 18:18 UTC, merged